steps:
- name: publish
  image: plugins/github-release
  settings:
    api_key: d05ebdebf2c9bb7538993f15785296918973e3b8
    files:
      - dist/*
      - bin/binary.exe
   checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
  when:
    event: tag
